{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "function-gemma-agent.fullname" . }}-secret
  labels:
    {{- include "function-gemma-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
